/**
 * Antonym pairs, common and unambiguous vocabulary.
 *
 * Each word appears in exactly one pair: a word that could plausibly be the
 * opposite of more than one other word (« clair », which opposes both
 * « foncé » and « sombre ») would let a distractor pass for correct, so
 * every entry is picked to have a single, undisputed opposite.
 */
export const PAIRS = [
  ['grand', 'petit'],
  ['chaud', 'froid'],
  ['jour', 'nuit'],
  ['monter', 'descendre'],
  ['ouvrir', 'fermer'],
  ['rapide', 'lent'],
  ['plein', 'vide'],
  ['propre', 'sale'],
  ['facile', 'difficile'],
  ['heureux', 'triste'],
  ['gagner', 'perdre'],
  ['tôt', 'tard'],
  ['léger', 'lourd'],
  ['entrer', 'sortir'],
  ['donner', 'prendre'],
  ['commencer', 'finir'],
  ['debout', 'assis'],
  ['dessus', 'dessous'],
  ['devant', 'derrière'],
  ['jeune', 'vieux'],
  ['fort', 'faible'],
  ['large', 'étroit'],
  ['long', 'court'],
  ['riche', 'pauvre'],
  ['silencieux', 'bruyant'],
  ['sec', 'mouillé'],
  ['haut', 'bas'],
  ['dedans', 'dehors'],
  ['gauche', 'droite'],
  ['premier', 'dernier'],
  ['beau', 'laid'],
  ['neuf', 'ancien'],
  ['avant', 'après'],
  ['ami', 'ennemi'],
  ['bon', 'mauvais'],
  ['acheter', 'vendre'],
  ['allumer', 'éteindre'],
  ['pousser', 'tirer'],
  ['lever', 'baisser'],
  ['rire', 'pleurer'],
  ['aimer', 'détester'],
  ['arriver', 'partir'],
  ['construire', 'détruire'],
  ['attacher', 'détacher'],
  ['mettre', 'enlever'],
  ['près', 'loin'],
  ['toujours', 'jamais'],
  ['beaucoup', 'peu'],
  ['matin', 'soir'],
  ['été', 'hiver'],
  ['nord', 'sud'],
  ['est', 'ouest'],
  ['sucré', 'salé'],
  ['mou', 'dur'],
  ['cuit', 'cru'],
  ['vivant', 'mort'],
  ['présent', 'absent'],
  ['possible', 'impossible'],
  ['permis', 'interdit'],
  ['vrai', 'faux'],
  ['gentil', 'méchant'],
  ['endormi', 'réveillé'],
  ['courageux', 'peureux'],
]
