/**
 * Sentences to complete, split into three series.
 *
 * Each item accepts a single correct answer: the distractors are valid words
 * on their own but wrong in this precise context, so the correction never
 * becomes a matter of opinion during a session.
 */
export const PHRASES = {
  meaning: [
    { before: 'Le boulanger sort le pain du', after: '.', answer: 'four', distractors: ['frigo', 'tiroir', 'placard'] },
    { before: 'Comme il pleuvait, Léa a ouvert son', after: '.', answer: 'parapluie', distractors: ['éventail', 'cartable', 'arrosoir'] },
    { before: 'Pour écrire son nom, Nina prend un', after: '.', answer: 'crayon', distractors: ['marteau', 'verre', 'coussin'] },
    { before: 'Le facteur dépose le courrier dans la', after: '.', answer: 'boîte aux lettres', distractors: ['poubelle', 'casserole', 'valise'] },
    { before: 'En hiver, quand il fait très froid, il tombe de la', after: '.', answer: 'neige', distractors: ['poussière', 'farine', 'fumée'] },
    { before: 'Pour découper le papier, Tom utilise des', after: '.', answer: 'ciseaux', distractors: ['lunettes', 'chaussettes', 'cuillères'] },
    { before: 'Le médecin écoute le cœur avec son', after: '.', answer: 'stéthoscope', distractors: ['téléphone', 'marteau', 'pinceau'] },
    { before: 'Nous avons planté des fleurs dans le', after: '.', answer: 'jardin', distractors: ['grenier', 'four', 'congélateur'] },
    { before: 'Le train entre en gare et s’arrête le long du', after: '.', answer: 'quai', distractors: ['trottoir', 'balcon', 'plafond'] },
    { before: 'Avant de traverser, on regarde des deux côtés de la', after: '.', answer: 'rue', distractors: ['cuisine', 'armoire', 'rivière'] },
    { before: 'Pour se brosser les dents, on met du', after: 'sur la brosse.', answer: 'dentifrice', distractors: ['shampooing', 'savon', 'vernis'] },
    { before: 'La nuit, pour éclairer sa chambre, Léo allume sa', after: '.', answer: 'lampe de chevet', distractors: ['télévision', 'radio', 'ventilateur'] },
    { before: 'Pour traverser la rivière, les habitants du village empruntent le', after: '.', answer: 'pont', distractors: ['mur', 'escalier', 'tunnel'] },
    { before: 'Le vendredi soir, papa allume un feu dans la', after: '.', answer: 'cheminée', distractors: ['cave', 'buanderie', 'véranda'] },
    { before: 'L’apiculteur récolte le miel dans la', after: '.', answer: 'ruche', distractors: ['grange', 'serre', 'cabane'] },
    { before: 'Pour se protéger du soleil, Emma met de la crème solaire et un', after: '.', answer: 'chapeau', distractors: ['pull', 'écharpe', 'gant'] },
    { before: 'Pour boire son jus d’orange, Inès prend un', after: '.', answer: 'verre', distractors: ['marteau', 'ballon', 'tapis'] },
    { before: 'Le soir, Hugo se couche dans son', after: '.', answer: 'lit', distractors: ['four', 'jardin', 'cartable'] },
    { before: 'Pour peindre sa maison, Papa utilise un', after: '.', answer: 'pinceau', distractors: ['stylo', 'peigne', 'râteau'] },
    { before: 'Les vaches broutent l’herbe dans le', after: '.', answer: 'pré', distractors: ['garage', 'salon', 'musée'] },
    { before: 'Pour couper le pain, Maman prend un', after: '.', answer: 'couteau', distractors: ['balai', 'parapluie', 'miroir'] },
    { before: 'Le pompier éteint l’incendie avec de l’', after: '.', answer: 'eau', distractors: ['huile', 'herbe', 'encre'] },
    { before: 'Pour dormir dehors, les campeurs montent une', after: '.', answer: 'tente', distractors: ['armoire', 'fenêtre', 'étagère'] },
    { before: 'Le matin, Chloé mange ses céréales dans un', after: '.', answer: 'bol', distractors: ['sac', 'seau', 'tapis'] },
    { before: 'Le bateau quitte le port et vogue sur la', after: '.', answer: 'mer', distractors: ['route', 'colline', 'prairie'] },
    { before: 'Pour ouvrir la porte, il faut tourner la', after: 'dans la serrure.', answer: 'clé', distractors: ['cuillère', 'plume', 'brosse'] },
    { before: 'Pour savoir quelle heure il est, je regarde ma', after: '.', answer: 'montre', distractors: ['trousse', 'brosse', 'chaise'] },
    { before: 'L’avion décolle de la piste de l’', after: '.', answer: 'aéroport', distractors: ['hôpital', 'boulangerie', 'bibliothèque'] },
    { before: 'Quand il fait nuit, on voit la lune et les', after: 'dans le ciel.', answer: 'étoiles', distractors: ['poissons', 'voitures', 'fourmis'] },
    { before: 'Le chat attrape une souris avec ses', after: '.', answer: 'griffes', distractors: ['ailes', 'nageoires', 'cornes'] },
    { before: 'Pour ranger ses habits, Zoé ouvre son', after: '.', answer: 'armoire', distractors: ['réfrigérateur', 'aquarium', 'grille-pain'] },
    { before: 'Avant de manger, on se lave les mains avec du', after: '.', answer: 'savon', distractors: ['sable', 'sucre', 'sirop'] },
    { before: 'Le cordonnier répare les', after: 'abîmées.', answer: 'chaussures', distractors: ['lunettes', 'montres', 'assiettes'] },
    { before: 'Pour regarder les étoiles, l’astronome utilise un', after: '.', answer: 'télescope', distractors: ['entonnoir', 'tournevis', 'aspirateur'] },
    { before: 'Au restaurant, le serveur apporte la', after: 'aux clients.', answer: 'carte', distractors: ['brouette', 'pelle', 'balançoire'] },
    { before: 'Pour semer des graines, le jardinier creuse la', after: '.', answer: 'terre', distractors: ['vitre', 'neige', 'farine'] },
  ],
  connectors: [
    { before: 'Voici la fille', after: 'habite en face.', answer: 'qui', distractors: ['que', 'dont', 'où'] },
    { before: 'Le livre', after: 'je t’ai parlé est passionnant.', answer: 'dont', distractors: ['que', 'qui', 'où'] },
    { before: 'C’est la ville', after: 'je suis né.', answer: 'où', distractors: ['que', 'qui', 'dont'] },
    { before: 'Elle mange la pomme', after: 'elle a lavée.', answer: 'qu’', distractors: ['qui', 'dont', 'où'] },
    { before: 'Il a enfin réussi', after: 'ouvrir la porte.', answer: 'à', distractors: ['de', 'par', 'en'] },
    { before: 'J’ai vraiment besoin', after: 'ton aide.', answer: 'de', distractors: ['à', 'par', 'pour'] },
    { before: 'Nous partons', after: 'Espagne cet été.', answer: 'en', distractors: ['au', 'à', 'dans'] },
    { before: 'Le train part', after: 'dix minutes.', answer: 'dans', distractors: ['depuis', 'pendant', 'il y a'] },
    { before: 'Il révise', after: 'd’être reçu à son examen.', answer: 'afin', distractors: ['bien', 'parce', 'pour que'] },
    { before: 'Elle est absente', after: 'elle est malade.', answer: 'parce qu’', distractors: ['afin qu’', 'bien qu’', 'pour qu’'] },
    { before: 'Voici le livre', after: 'je préfère.', answer: 'que', distractors: ['qui', 'dont', 'où'] },
    { before: 'Il pleut fort,', after: 'nous restons à la maison.', answer: 'donc', distractors: ['mais', 'car', 'or'] },
    { before: 'Elle chante', after: 'elle se coiffe.', answer: 'pendant qu’', distractors: ['bien qu’', 'dès qu’', 'parce qu’'] },
    { before: 'Range tes affaires', after: 'elles ne traînent plus.', answer: 'pour que', distractors: ['parce que', 'bien que', 'dès que'] },
    { before: 'Il fait ses devoirs', after: 'sortir jouer.', answer: 'avant de', distractors: ['après', 'pendant', 'depuis'] },
    { before: 'Elle a réussi son examen', after: 'avoir beaucoup travaillé.', answer: 'après', distractors: ['avant', 'pendant', 'dès'] },
    { before: 'Voici le garçon', after: 'a gagné la course.', answer: 'qui', distractors: ['que', 'dont', 'où'] },
    { before: 'Le gâteau', after: 'Maman a préparé est délicieux.', answer: 'que', distractors: ['qui', 'dont', 'où'] },
    { before: 'Le village', after: 'nous passons nos vacances est très calme.', answer: 'où', distractors: ['que', 'qui', 'dont'] },
    { before: 'L’ami', after: 'je te parle arrive demain.', answer: 'dont', distractors: ['que', 'qui', 'où'] },
    { before: 'Elle est partie', after: 'il pleuvait.', answer: 'bien qu’', distractors: ['parce qu’', 'afin qu’', 'dès qu’'] },
    { before: 'Il a mis son manteau', after: 'il avait froid.', answer: 'parce qu’', distractors: ['bien qu’', 'afin qu’', 'avant qu’'] },
    { before: 'Nous mangerons', after: 'Papa sera rentré.', answer: 'dès que', distractors: ['bien que', 'parce que', 'afin que'] },
    { before: 'Il court vite', after: 'gagner la course.', answer: 'pour', distractors: ['car', 'mais', 'donc'] },
    { before: 'J’aime le chocolat,', after: 'je n’aime pas la vanille.', answer: 'mais', distractors: ['donc', 'car', 'ou'] },
    { before: 'Veux-tu du thé', after: 'du café ?', answer: 'ou', distractors: ['où', 'mais', 'donc'] },
    { before: 'Il a beaucoup couru,', after: 'il est fatigué.', answer: 'donc', distractors: ['mais', 'ou', 'et'] },
    { before: 'Elle ne sort pas', after: 'elle est enrhumée.', answer: 'car', distractors: ['donc', 'mais', 'ou'] },
    { before: 'Il a appris à nager', after: 'avoir peur de l’eau.', answer: 'sans', distractors: ['pour', 'avec', 'vers'] },
    { before: 'Nous sommes allés au parc', after: 'la pluie.', answer: 'malgré', distractors: ['grâce à', 'selon', 'depuis'] },
    { before: 'Elle réussit', after: 'à son travail.', answer: 'grâce', distractors: ['malgré', 'sans', 'contre'] },
    { before: 'Il a dormi', after: 'toute la nuit.', answer: 'pendant', distractors: ['pour', 'dans', 'sur'] },
    { before: 'Nous habitons ici', after: 'dix ans.', answer: 'depuis', distractors: ['pour', 'sans', 'chez'] },
    { before: 'Le chat se cache', after: 'le canapé.', answer: 'derrière', distractors: ['pendant', 'depuis', 'pourtant'] },
    { before: 'La voiture est garée', after: 'la maison.', answer: 'devant', distractors: ['pendant', 'avant', 'pourtant'] },
    { before: 'Range ton cartable', after: 'de partir.', answer: 'avant', distractors: ['après', 'depuis', 'pendant'] },
  ],
  agreement: [
    { before: 'Les enfants', after: 'dans la cour.', answer: 'jouent', distractors: ['joue', 'jouez', 'jouons'] },
    { before: 'La petite fille', after: 'heureuse.', answer: 'est', distractors: ['sont', 'es', 'êtes'] },
    { before: 'Mes chaussures sont toutes', after: '.', answer: 'neuves', distractors: ['neuf', 'neuve', 'neufs'] },
    { before: 'Ils', after: 'partis très tôt ce matin.', answer: 'sont', distractors: ['ont', 'est', 'a'] },
    { before: 'Elle a', after: 'une lettre à sa tante.', answer: 'écrit', distractors: ['écrite', 'écrits', 'écrites'] },
    { before: 'Les fleurs que j’ai', after: 'sont déjà fanées.', answer: 'cueillies', distractors: ['cueilli', 'cueillie', 'cueillis'] },
    { before: 'Tu', after: 'ton manteau avant de sortir.', answer: 'mets', distractors: ['met', 'mettent', 'mettes'] },
    { before: 'Nous', after: 'au cinéma hier soir.', answer: 'sommes allés', distractors: ['est allé', 'sont allés', 'avons allé'] },
    { before: 'Ce sont des livres très', after: '.', answer: 'intéressants', distractors: ['intéressant', 'intéressante', 'intéressantes'] },
    { before: 'Chaque élève', after: 'son cahier.', answer: 'apporte', distractors: ['apportent', 'apportes', 'apporter'] },
    { before: 'Le chat', after: 'sur le canapé.', answer: 'dort', distractors: ['dorment', 'dors', 'dormez'] },
    { before: 'Ces gâteaux sont', after: '.', answer: 'délicieux', distractors: ['délicieuse', 'délicieuses', 'délicieusement'] },
    { before: 'Vous êtes tous', after: 'à la fête.', answer: 'invités', distractors: ['invité', 'invitée', 'invitées'] },
    { before: 'Elle a', after: 'toutes les fenêtres avant de partir.', answer: 'fermé', distractors: ['fermée', 'fermées', 'fermés'] },
    { before: 'Les vestes sont', after: '.', answer: 'chaudes', distractors: ['chaud', 'chauds', 'chaude'] },
    { before: 'Chaque matin, je', after: 'mon vélo pour aller à l’école.', answer: 'prends', distractors: ['prend', 'prenons', 'prenez'] },
    { before: 'Mes sœurs', after: 'toujours en retard.', answer: 'sont', distractors: ['est', 'ont', 'es'] },
    { before: 'Les oiseaux', after: 'dans le ciel.', answer: 'volent', distractors: ['vole', 'voles', 'volez'] },
    { before: 'Nous', after: 'une glace à la fraise.', answer: 'mangeons', distractors: ['mange', 'mangez', 'mangent'] },
    { before: 'Vous', after: 'très vite.', answer: 'courez', distractors: ['court', 'courent', 'courons'] },
    { before: 'La voiture est', after: 'dans le garage.', answer: 'garée', distractors: ['garé', 'garés', 'garées'] },
    { before: 'Les filles sont', after: 'à l’école.', answer: 'arrivées', distractors: ['arrivé', 'arrivée', 'arrivés'] },
    { before: 'Mon frère est très', after: '.', answer: 'grand', distractors: ['grande', 'grands', 'grandes'] },
    { before: 'Ma voisine est très', after: '.', answer: 'gentille', distractors: ['gentil', 'gentils', 'gentilles'] },
    { before: 'Les robes de Léa sont très', after: '.', answer: 'jolies', distractors: ['joli', 'jolie', 'jolis'] },
    { before: 'Elle a', after: 'ses devoirs ce matin.', answer: 'fini', distractors: ['finie', 'finis', 'finies'] },
    { before: 'Les cerises que Léa a', after: 'étaient bonnes.', answer: 'mangées', distractors: ['mangé', 'mangée', 'mangés'] },
    { before: 'Tu', after: 'tes chaussures avant d’entrer.', answer: 'enlèves', distractors: ['enlève', 'enlèvent', 'enlevez'] },
    { before: 'Je', after: 'le journal tous les matins.', answer: 'lis', distractors: ['lit', 'lisent', 'lisons'] },
    { before: 'Les élèves', after: 'leur leçon en silence.', answer: 'récitent', distractors: ['récite', 'récites', 'récitez'] },
    { before: 'Ces fleurs sont', after: 'comme des étoiles.', answer: 'blanches', distractors: ['blanc', 'blanche', 'blancs'] },
    { before: 'Mes parents m’ont', after: 'un beau cadeau.', answer: 'offert', distractors: ['offerte', 'offerts', 'offertes'] },
    { before: 'Hier soir, nous sommes', after: 'au théâtre.', answer: 'allés', distractors: ['allé', 'allée', 'allées'] },
    { before: 'La classe', after: 'une sortie au musée.', answer: 'prépare', distractors: ['préparent', 'prépares', 'préparez'] },
    { before: 'Quand il pleut, mes bottes sont toutes', after: '.', answer: 'mouillées', distractors: ['mouillé', 'mouillée', 'mouillés'] },
    { before: 'Ils', after: 'leur chambre ensemble.', answer: 'rangent', distractors: ['range', 'ranges', 'rangez'] },
  ],
}

export const SERIES = {
  meaning: 'Sens de la phrase',
  connectors: 'Mots de liaison',
  agreement: 'Accords',
}
