/**
 * Words split into written syllables. The split follows school practice
 * (one vowel per syllable, double consonants separated).
 */
export const WORDS = {
  2: [
    ['ba', 'teau'],
    ['ca', 'nard'],
    ['mai', 'son'],
    ['la', 'pin'],
    ['che', 'val'],
    ['ta', 'pis'],
    ['sou', 'ris'],
    ['ca', 'deau'],
    ['vé', 'lo'],
    ['jar', 'din'],
    ['mou', 'ton'],
    ['sa', 'von'],
    ['gâ', 'teau'],
    ['fo', 'rêt'],
    ['dan', 'ser'],
    ['pou', 'let'],
    ['ru', 'ban'],
    ['bal', 'lon'],
    ['sa', 'lon'],
    ['ra', 'dis'],
    ['bu', 'reau'],
    ['ri', 'deau'],
  ],
  3: [
    ['cho', 'co', 'lat'],
    ['pa', 'pil', 'lon'],
    ['bi', 'be', 'ron'],
    ['do', 'mi', 'no'],
    ['ma', 'ga', 'sin'],
    ['pa', 'ra', 'pluie'],
    ['ca', 'ra', 'mel'],
    ['ta', 'bou', 'ret'],
    ['es', 'car', 'got'],
    ['ha', 'ri', 'cot'],
    ['pan', 'ta', 'lon'],
    ['ba', 'lan', 'çoire'],
    ['pé', 'li', 'can'],
    ['ca', 'len', 'drier'],
    ['kan', 'gou', 'rou'],
    ['di', 'no', 'saure'],
    ['am', 'bu', 'lance'],
    ['four', 'mi', 'lière'],
    ['coc', 'ci', 'nelle'],
    ['to', 'bog', 'gan'],
  ],
  4: [
    ['or', 'di', 'na', 'teur'],
    ['té', 'lé', 'vi', 'sion'],
    ['a', 'ni', 'ma', 'teur'],
    ['an', 'ni', 'ver', 'saire'],
    ['ha', 'bi', 'ta', 'tion'],
    ['in', 'for', 'ma', 'tion'],
    ['cal', 'cu', 'la', 'teur'],
    ['ré', 'cré', 'a', 'tion'],
    ['hé', 'li', 'cop', 'tère'],
    ['ma', 'ga', 'si', 'nier'],
    ['ta', 'pis', 'se', 'rie'],
    ['co', 'lo', 'ri', 'age'],
    ['ki', 'lo', 'gram', 'me'],
    ['pa', 'ra', 'chu', 'tiste'],
    ['pa', 'pe', 'te', 'rie'],
    ['au', 'to', 'mo', 'bile'],
  ],
}
