/**
 * Target words and orthographically close lures: letter inversions, visual
 * confusions (b/d, p/q, m/n) and added or missing letters. The lures are
 * written by hand so they stay believable.
 */
export const SHORT_WORDS = [
  { word: 'bain', distractors: ['dain', 'bian', 'brin'] },
  { word: 'pont', distractors: ['pomt', 'ponc', 'plont'] },
  { word: 'dent', distractors: ['bent', 'dnet', 'dant'] },
  { word: 'chat', distractors: ['chad', 'cath', 'chait'] },
  { word: 'pluie', distractors: ['pulie', 'pliue', 'bluie'] },
  { word: 'train', distractors: ['tarin', 'trian', 'drain'] },
  { word: 'ferme', distractors: ['frem', 'fenne', 'ferne'] },
  { word: 'porte', distractors: ['prote', 'porde', 'potre'] },
  { word: 'brique', distractors: ['birque', 'briqe', 'drique'] },
  { word: 'monde', distractors: ['mnode', 'monbe', 'nonde'] },
  { word: 'lune', distractors: ['lume', 'lnue', 'lunne'] },
  { word: 'jupe', distractors: ['jube', 'jupp', 'jpue'] },
  { word: 'mare', distractors: ['nare', 'mrae', 'marre'] },
  { word: 'vase', distractors: ['vaze', 'vsae', 'vasse'] },
  { word: 'banc', distractors: ['danc', 'bnac', 'banq'] },
  { word: 'lampe', distractors: ['nampe', 'lanpe', 'lampme'] },
  { word: 'bulle', distractors: ['dulle', 'bulla', 'bulel'] },
  { word: 'cloche', distractors: ['closhe', 'colche', 'clohce'] },
  { word: 'tigre', distractors: ['digre', 'tirge', 'tigrre'] },
  { word: 'poule', distractors: ['boule', 'poulle', 'pouel'] },
  { word: 'nuit', distractors: ['nuti', 'muit', 'nuiit'] },
  { word: 'pomme', distractors: ['pomne', 'ponme', 'pome'] },
  { word: 'table', distractors: ['tabel', 'dable', 'tabble'] },
  { word: 'soupe', distractors: ['sobpe', 'soupé', 'soupde'] },
  { word: 'plage', distractors: ['plaje', 'blage', 'palge'] },
  { word: 'neige', distractors: ['neidge', 'nieige', 'neigue'] },
  { word: 'grand', distractors: ['grnad', 'qrand', 'grant'] },
  { word: 'verre', distractors: ['vrere', 'verne', 'berre'] },
  { word: 'ballon', distractors: ['dallon', 'balon', 'ballom'] },
  { word: 'livre', distractors: ['lirve', 'livne', 'ilvre'] },
  { word: 'route', distractors: ['rotue', 'routte', 'ronte'] },
  { word: 'arbre', distractors: ['arbe', 'arbne', 'abrre'] },
  { word: 'gomme', distractors: ['gonme', 'qomme', 'gome'] },
  { word: 'fleur', distractors: ['fluer', 'fleue', 'fleuz'] },
  { word: 'piano', distractors: ['pinao', 'biano', 'pianno'] },
  { word: 'sable', distractors: ['sabel', 'sadle', 'sabbe'] },
  { word: 'moto', distractors: ['mato', 'mote', 'noto'] },
  { word: 'robe', distractors: ['rode', 'rober', 'rbbe'] },
  { word: 'canard', distractors: ['canrad', 'canart', 'canand'] },
  { word: 'cheval', distractors: ['chevla', 'chevel', 'chevai'] },
]

export const LONG_WORDS = [
  { word: 'lapin', distractors: ['lipan', 'lapun', 'labin'] },
  { word: 'tablier', distractors: ['tablire', 'talbier', 'tabiler'] },
  { word: 'chameau', distractors: ['chameu', 'chamaeu', 'chameua'] },
  { word: 'fenêtre', distractors: ['fentêre', 'fenêrte', 'fnêetre'] },
  { word: 'escalier', distractors: ['escalire', 'escaiier', 'esclaier'] },
  { word: 'pantalon', distractors: ['pantolan', 'pantalom', 'pantlaon'] },
  { word: 'bouteille', distractors: ['boutielle', 'bouteile', 'doutéille'] },
  { word: 'crocodile', distractors: ['crocodlie', 'crocidole', 'crocodible'] },
  { word: 'printemps', distractors: ['pritemps', 'prinstemp', 'printemsp'] },
  { word: 'dictionnaire', distractors: ['dictionaire', 'dicitonnaire', 'distionnaire'] },
  { word: 'papillon', distractors: ['bapillon', 'papillion', 'papyllon'] },
  { word: 'ordinateur', distractors: ['erdinateur', 'ordinateru', 'ordinnateur'] },
  { word: 'téléphone', distractors: ['délephone', 'télephonne', 'télephnoe'] },
  { word: 'chocolat', distractors: ['chocolot', 'chocolta', 'checolat'] },
  { word: 'montagne', distractors: ['montagme', 'montange', 'motangne'] },
  { word: 'aquarium', distractors: ['aquarum', 'aqarium', 'aquariun'] },
  { word: 'parapluie', distractors: ['parapluue', 'paraplule', 'parapuile'] },
  { word: 'ambulance', distractors: ['anbulance', 'ambulence', 'ambulanse'] },
  { word: 'kangourou', distractors: ['kangorou', 'kangoutou', 'kangourouu'] },
  { word: 'toboggan', distractors: ['tobogan', 'tobbogan', 'toboggam'] },
  { word: 'éléphant', distractors: ['élépahnt', 'éléphan', 'élèphant'] },
  { word: 'hirondelle', distractors: ['hirondele', 'hirondlle', 'hirodelle'] },
  { word: 'bibliothèque', distractors: ['bibliotèque', 'bilbiothèque', 'dibliothèque'] },
  { word: 'pharmacie', distractors: ['farmacie', 'pharamcie', 'pharmacei'] },
  { word: 'boulangerie', distractors: ['boulangrie', 'doulangerie', 'boulagnerie'] },
  { word: 'trottinette', distractors: ['trotinette', 'trottinnete', 'trotinettte'] },
  { word: 'champignon', distractors: ['champigon', 'chanpignon', 'champingon'] },
  { word: 'hélicoptère', distractors: ['hélicotpère', 'hélicoptere', 'hélicoptèrre'] },
  { word: 'baignoire', distractors: ['baignoir', 'daignoire', 'baingoire'] },
  { word: 'girafe', distractors: ['jirafe', 'girrafe', 'giraffe'] },
  { word: 'araignée', distractors: ['araigné', 'araingée', 'aragnée'] },
  { word: 'grenouille', distractors: ['grenouile', 'grenoulle', 'grnouille'] },
  { word: 'hérisson', distractors: ['hérison', 'herrisson', 'hérrison'] },
  { word: 'bicyclette', distractors: ['bicyclete', 'bycyclette', 'bicylcette'] },
  { word: 'médicament', distractors: ['médicamant', 'médiacment', 'médicamment'] },
  { word: 'supermarché', distractors: ['supermarche', 'supermarhcé', 'sumermarché'] },
  { word: 'calculatrice', distractors: ['calculatrise', 'calculatirce', 'calcualtrice'] },
  { word: 'dromadaire', distractors: ['dromadair', 'dromedaire', 'drpmadaire'] },
  { word: 'cinéma', distractors: ['cinema', 'sinéma', 'cineéma'] },
  { word: 'stylo', distractors: ['stilo', 'styl', 'sstylo'] },
]
