import { useEffect, useState } from 'react'
import Icon from './Icon.jsx'
import Modal from './Modal.jsx'
import { version as currentVersion } from '../../package.json'

const STORAGE_KEY = 'orthobox:lastSeenVersion'

/**
 * `public/whats-new.json`'s highlights for the current version, or `null` if
 * there is nothing to show (missing file, a different version, no
 * highlights).
 */
function fetchHighlights() {
  return fetch('./whats-new.json')
    .then((response) => (response.ok ? response.json() : null))
    .then((data) => {
      if (!data || data.version !== currentVersion) return null
      return Array.isArray(data.highlights) && data.highlights.length > 0 ? data.highlights : null
    })
    .catch(() => null)
}

/**
 * "What's new" bell: shows the release highlights on demand, and once on
 * its own the first time the application runs on a version different from
 * the one last recorded — a first-ever visit only records the version,
 * quietly, nothing to compare it against yet.
 *
 * The highlights come from `public/whats-new.json`, a short, French,
 * user-facing summary regenerated by the release workflow for every
 * version — never the technical CHANGELOG.md. That generation step can
 * fail silently (see release-please.yml), so the bell doubles as a way to
 * check "did this release actually get one?" rather than only ever
 * popping up unannounced.
 */
export default function WhatsNew() {
  const [content, setContent] = useState(null)

  useEffect(() => {
    let lastSeen
    try {
      lastSeen = window.localStorage.getItem(STORAGE_KEY)
    } catch {
      return undefined
    }

    if (lastSeen === null) {
      try {
        window.localStorage.setItem(STORAGE_KEY, currentVersion)
      } catch {
        /* Storage unavailable: nothing to track, nothing to show. */
      }
      return undefined
    }

    if (lastSeen === currentVersion) return undefined

    let active = true
    fetchHighlights().then((highlights) => {
      if (active && highlights) setContent(highlights)
    })
    return () => {
      active = false
    }
  }, [])

  const close = () => {
    setContent(null)
    try {
      window.localStorage.setItem(STORAGE_KEY, currentVersion)
    } catch {
      /* ignore */
    }
  }

  // Clicking the bell always opens the popup, unlike the automatic check
  // above: a click is an explicit request, so it gets an answer either way
  // — the highlights if there are any, otherwise a plain "nothing new" note
  // rather than silence that reads as broken.
  const showManually = () => {
    fetchHighlights().then((highlights) => {
      setContent(highlights ?? [])
    })
  }

  return (
    <>
      <button
        type="button"
        className="icon-round"
        aria-label="Nouveautés de la version"
        onClick={showManually}
      >
        <Icon name="bell" size={18} filled={false} />
      </button>

      {content && (
        <Modal
          titleId="whats-new-title"
          title={`🎉 Nouveautés de la version ${currentVersion}`}
          onClose={close}
        >
          {content.length > 0 ? (
            <ul className="whats-new__list">
              {content.map((line) => (
                <li key={line}>{line}</li>
              ))}
            </ul>
          ) : (
            <p className="modal__text">Rien de neuf à signaler pour cette version.</p>
          )}
        </Modal>
      )}
    </>
  )
}
