import { useEffect, useState } from 'react'
import Modal from './Modal.jsx'
import { version as currentVersion } from '../../package.json'

const STORAGE_KEY = 'orthobox:lastSeenVersion'

/**
 * "What's new" popup: shown once, the first time the application runs on a
 * version different from the one last recorded.
 *
 * The highlights come from `public/whats-new.json`, a short, French,
 * user-facing summary regenerated by the release workflow for every
 * version — never the technical CHANGELOG.md. A first-ever visit only
 * records the current version, quietly: nothing to compare it against yet.
 */
export default function WhatsNew() {
  const [highlights, setHighlights] = useState(null)

  useEffect(() => {
    let lastSeen
    try {
      lastSeen = window.localStorage.getItem(STORAGE_KEY)
    } catch {
      return undefined
    }

    if (lastSeen === null) {
      try {
        window.localStorage.setItem(STORAGE_KEY, currentVersion)
      } catch {
        /* Storage unavailable: nothing to track, nothing to show. */
      }
      return undefined
    }

    if (lastSeen === currentVersion) return undefined

    let active = true
    fetch('./whats-new.json')
      .then((response) => (response.ok ? response.json() : null))
      .then((data) => {
        if (!active || !data || data.version !== currentVersion) return
        if (Array.isArray(data.highlights) && data.highlights.length > 0) {
          setHighlights(data.highlights)
        }
      })
      .catch(() => {})

    return () => {
      active = false
    }
  }, [])

  const close = () => {
    setHighlights(null)
    try {
      window.localStorage.setItem(STORAGE_KEY, currentVersion)
    } catch {
      /* ignore */
    }
  }

  if (!highlights) return null

  return (
    <Modal
      titleId="whats-new-title"
      title={`Nouveautés de la version ${currentVersion}`}
      onClose={close}
    >
      <ul className="whats-new__list">
        {highlights.map((line) => (
          <li key={line}>{line}</li>
        ))}
      </ul>
    </Modal>
  )
}
